language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

matrix:
    exclude:
        - php: 5.6
          env: SYMFONY_VERSION=4.0.*
        - php: 7.0
          env: SYMFONY_VERSION=4.0.*
    fast_finish: true

services:
    - mongodb

env:
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=3.1.*
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=3.3.*
    - SYMFONY_VERSION=4.0.*

before_install:
    - if [[ "$STABLE" != "" ]]; then composer config minimum-stability $STABLE; fi;

before_script:
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - if [[ $TRAVIS_PHP_VERSION =~ ^5 ]]; then echo 'extension = "mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if ! [[ $TRAVIS_PHP_VERSION =~ ^5 ]]; then echo 'extension = "mongodb.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - composer self-update
    - if ! [[ $TRAVIS_PHP_VERSION =~ ^5 ]]; then composer require alcaeus/mongo-php-adapter:1.0.* --ignore-platform-reqs; fi;
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/form:${SYMFONY_VERSION} --no-update
    - composer update

script:
    - phpunit
